insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Carmelina', 'Lening', 'clening0@symantec.com', '1055484612', 'Street', 79404, 'Tepusteca', '1986377421');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Deina', 'Devany', 'ddevany1@blogger.com', '1048188043', 'Drive', 50773, 'Yongfeng', '8561644894');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Luther', 'Bernardotte', 'lbernardotte2@irs.gov', '3669868143', 'Place', 47845, 'Chemodanovka', '6413705196');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Pen', 'Feltham', 'pfeltham3@pinterest.com', '3235056289', 'Street', 35420, 'Paraná', '3183013892');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Anita', 'Parsell', 'aparsell4@odnoklassniki.ru', '7382209377', 'Terrace', 15412, 'Magoúla', '6275077185');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Becka', 'Ricci', 'bricci5@aboutads.info', '2201322880', 'Center', 29527, 'Panikihan', '8712948536');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Electra', 'Pounds', 'epounds6@nasa.gov', '7560052258', 'Road', 85598, 'Mysove', '3017387836');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Mirna', 'Weeden', 'mweeden7@seattletimes.com', '5491447072', 'Avenue', 29830, 'Lajas', '7014297868');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Shalna', 'Adamiec', 'sadamiec8@taobao.com', '3801780201', 'Alley', 66223, 'São Gonçalo do Amarante', '9907265971');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Michele', 'Itzkovsky', 'mitzkovsky9@berkeley.edu', '7600388383', 'Terrace', 91386, 'Sambungjaya', '2753879425');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Uri', 'Simonutti', 'usimonuttia@e-recht24.de', '0651429617', 'Avenue', 11077, 'Malamig', '3599880156');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Rodolfo', 'Prew', 'rprewb@barnesandnoble.com', '3180811897', 'Trail', 93245, 'Ocumare del Tuy', '8559130830');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Harmon', 'Cholomin', 'hcholominc@desdev.cn', '9231580566', 'Parkway', 97956, 'Sasovo', '3115878563');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Bay', 'Simonini', 'bsimoninid@dailymail.co.uk', '5837443983', 'Plaza', 27930, 'Kahrīz', '8967297334');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Melly', 'Strover', 'mstrovere@discovery.com', '6760099400', 'Point', 65404, 'Oliveira', '8454098108');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Darci', 'Hamm', 'dhammf@rambler.ru', '9912842596', 'Pass', 92868, 'Leigongjian', '7192911730');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Noam', 'Rhoades', 'nrhoadesg@yolasite.com', '6931818708', 'Park', 34982, 'Cikulina', '2316426054');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Sydel', 'Erwin', 'serwinh@taobao.com', '5650910448', 'Pass', 62788, 'Yizhang Chengguanzhen', '9176822351');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Sheree', 'Wreak', 'swreaki@fda.gov', '0617721009', 'Lane', 71070, 'Anle', '4643936575');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Leigh', 'Jotham', 'ljothamj@auda.org.au', '8457732773', 'Hill', 17980, 'Lom Sak', '1335248321');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Ethe', 'Rickerby', 'erickerbyk@illinois.edu', '9516124488', 'Hill', 25693, 'Hor', '5709997148');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Daven', 'Quinane', 'dquinanel@yellowbook.com', '5116879526', 'Terrace', 53268, 'Los Algarrobos', '3223319302');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Norma', 'Jandl', 'njandlm@furl.net', '6036156308', 'Circle', 48751, 'Yamrat', '4043499703');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Arda', 'Paz', 'apazn@timesonline.co.uk', '1475852290', 'Court', 54539, 'Zamora', '7609322892');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Mathew', 'Zapata', 'mzapatao@php.net', '2372946048', 'Place', 42844, 'Hantsport', '4502099685');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Bridgette', 'Bartolomeoni', 'bbartolomeonip@nydailynews.com', '4474987713', 'Road', 96858, 'Shiogama', '4472643333');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Shaylah', 'Seymark', 'sseymarkq@mozilla.org', '2342474946', 'Street', 19684, 'Rancabugel', '4527933060');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Yoshiko', 'Iacovelli', 'yiacovellir@lycos.com', '1542633990', 'Street', 73153, 'Bani', '2974625729');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Prudence', 'Corro', 'pcorros@oakley.com', '2299211381', 'Road', 55180, 'Bauru', '9084288609');
insert into student (first_name, sur_name, email, person_number, street, zip, city, phone) values ('Hailee', 'MacCartney', 'hmaccartneyt@google.fr', '1342979214', 'Pass', 57687, 'Quiñota', '6433757501');

insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Reine', 'Logsdale', 'rlogsdale0@digg.com', false, '3882389257', 'Monterey', 'Gizel’', 73036, '9984841561');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Cristobal', 'Peach', 'cpeach1@twitter.com', true, '7223766379', 'Gateway', 'Fucheng', 78210, '5344041527');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Pearle', 'Ifill', 'pifill2@wordpress.org', true, '0939560852', 'Dawn', 'Malkā', 15875, '4641218110');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Saxe', 'Flode', 'sflode3@pbs.org', true, '1854365231', 'Farwell', 'Jiqu', 26412, '0345532376');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Ambur', 'Asgodby', 'aasgodby4@cmu.edu', true, '8752208591', 'Miller', 'Quatro Barras', 99028, '9012413079');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Ketty', 'Bouchard', 'kbouchard5@domainmarket.com', true, '6269431166', 'Division', 'Nova Odesa', 79277, '1518364667');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Jerri', 'Prime', 'jprime6@dot.gov', true, '7903872346', 'Darwin', 'Hengshi', 10851, '7481719489');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Danila', 'Schlagtmans', 'dschlagtmans7@hp.com', false, '6317382891', 'Chinook', 'Kepel', 84700, '8408378511');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Inessa', 'Brissard', 'ibrissard8@youtu.be', true, '0532552423', 'Larry', 'Elx/Elche', 38771, '2197658522');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Arda', 'Pettwood', 'apettwood9@tripadvisor.com', true, '0759092419', 'Nova', 'Huangdao', 74622, '1740535901');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Horatius', 'Laffan', 'hlaffana@zimbio.com', true, '8834684141', 'Cascade', 'Novyy Nekouz', 46533, '0076214532');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Joelle', 'Gabriel', 'jgabrielb@chicagotribune.com', true, '0519014685', 'Fieldstone', 'Santo Ângelo', 99745, '9875089362');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Jayson', 'Grammer', 'jgrammerc@hibu.com', true, '6135993224', 'South', 'Waitangi', 22477, '9978466169');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Rocky', 'Dengel', 'rdengeld@tamu.edu', true, '8720014708', 'Division', 'Shāhpur', 91688, '9861356797');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Mair', 'Mahon', 'mmahone@youtu.be', true, '8589865878', 'Eggendart', 'Zagreb', 68600, '3190590206');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Tye', 'Lafranconi', 'tlafranconif@clickbank.net', false, '7119628313', 'Corben', 'Takanini', 54060, '5408671232');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Caryl', 'Winterbottom', 'cwinterbottomg@miibeian.gov.cn', true, '0497022931', 'Carberry', 'Takanosu', 43594, '8828848170');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Alberta', 'Leppard', 'aleppardh@creativecommons.org', false, '7791417634', 'Blue Bill Park', 'Pag', 62106, '4762728063');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Barron', 'Parmeter', 'bparmeteri@deviantart.com', true, '4190555614', 'Luster', 'Ivry-sur-Seine', 79582, '5025162378');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Katharyn', 'Dykes', 'kdykesj@economist.com', true, '9328059801', 'Toban', 'Malikisi', 61195, '2756894184');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Branden', 'Yaus', 'byausk@eepurl.com', false, '7100626633', 'Johnson', 'Lututów', 53538, '7859171015');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Brandtr', 'Readwin', 'breadwinl@php.net', true, '2028820047', 'Susan', 'Tajinan', 84637, '9405997645');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Eziechiele', 'Monks', 'emonksm@booking.com', false, '4658212897', 'Fulton', 'Itagüí', 23682, '8391945189');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Eveleen', 'Nuccii', 'enucciin@g.co', true, '9772636832', 'Dayton', 'Qinlan', 32260, '2701843634');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Stanleigh', 'Cumberland', 'scumberlando@addtoany.com', false, '6511868737', 'Bobwhite', 'Cirateun', 40544, '4533161103');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Had', 'Andrez', 'handrezp@a8.net', false, '0638413311', 'Toban', 'Ariz', 55166, '1036271684');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Ursuline', 'Tuffin', 'utuffinq@icq.com', false, '0638502020', 'Merry', 'Raydah', 41324, '2755697458');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Tim', 'Alliban', 'tallibanr@google.pl', true, '4777733262', 'Susan', 'Supu', 95212, '8804706767');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Earlie', 'Huxster', 'ehuxsters@google.ru', true, '3457075506', 'Little Fleur', 'Yongfeng', 85356, '3129220216');
insert into instructor (first_name, sur_name, email, ensamble, person_number, street, city, zip, phone) values ('Aigneis', 'Cumbridge', 'acumbridget@bizjournals.com', false, '9306912439', 'Derek', 'Reims', 18768, '0243121288');


insert into instructor_teach_instrument (instructor_id, level , instrument ) values (26, 'advanced', 'double bass');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (4, 'intermediate', 'piano');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (18, 'intermediate', 'guitar');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (27, 'beginner', 'clarinett');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (26, 'intermediate', 'fiol');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (16, 'intermediate', 'guitar');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (12, 'beginner', 'violin');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (25, 'intermediate', 'piano');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (21, 'beginner', 'double bass');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (5, 'advanced', 'guitar');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (21, 'advanced', 'guitar');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (5, 'advanced', 'harmonica');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (28, 'intermediate', 'double bass');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (27, 'intermediate', 'piano');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (5, 'advanced', 'fiol');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (2, 'intermediate', 'clarinett');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (22, 'intermediate', 'double bass');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (24, 'beginner', 'trumpet');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (21, 'advanced', 'saxophone');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (24, 'advanced', 'double bass');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (30, 'beginner', 'clarinett');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (9, 'intermediate', 'harmonica');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (15, 'beginner', 'saxophone');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (7, 'intermediate', 'double bass');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (14, 'advanced', 'violin');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (4, 'beginner', 'guitar');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (4, 'intermediate', 'saxophone');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (11, 'advanced', 'fiol');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (1, 'intermediate', 'cello');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (16, 'beginner', 'clarinett');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (10, 'beginner', 'piano');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (13, 'advanced', 'fiol');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (15, 'advanced', 'piano');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (29, 'beginner', 'violin');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (12, 'beginner', 'cello');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (15, 'beginner', 'saxophone');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (28, 'beginner', 'piano');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (23, 'beginner', 'fiol');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (25, 'advanced', 'piano');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (20, 'intermediate', 'double bass');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (18, 'advanced', 'harmonica');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (13, 'advanced', 'violin');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (23, 'beginner', 'piano');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (7, 'advanced', 'harmonica');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (13, 'intermediate', 'double bass');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (7, 'beginner', 'cello');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (6, 'advanced', 'harmonica');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (2, 'advanced', 'trumpet');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (17, 'advanced', 'fiol');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (18, 'advanced', 'violin');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (30, 'beginner', 'trumpet');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (16, 'intermediate', 'fiol');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (9, 'beginner', 'piano');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (20, 'beginner', 'cello');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (3, 'beginner', 'saxophone');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (27, 'advanced', 'saxophone');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (23, 'advanced', 'harmonica');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (10, 'intermediate', 'cello');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (7, 'intermediate', 'cello');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (20, 'advanced', 'fiol');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (21, 'intermediate', 'harmonica');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (12, 'advanced', 'double bass');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (3, 'beginner', 'clarinett');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (2, 'advanced', 'double bass');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (28, 'intermediate', 'saxophone');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (28, 'intermediate', 'clarinett');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (23, 'advanced', 'saxophone');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (11, 'advanced', 'saxophone');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (11, 'beginner', 'piano');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (28, 'intermediate', 'piano');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (28, 'beginner', 'cello');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (19, 'beginner', 'fiol');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (12, 'intermediate', 'double bass');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (2, 'advanced', 'clarinett');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (6, 'beginner', 'cello');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (30, 'intermediate', 'harmonica');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (19, 'beginner', 'violin');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (27, 'beginner', 'saxophone');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (19, 'advanced', 'harmonica');
insert into instructor_teach_instrument (instructor_id, level , instrument ) values (16, 'advanced', 'saxophone');


insert into instrument_in_stock (instrument, brand , rented) values ('guitar', 'Fender Musical', false);
insert into instrument_in_stock (instrument, brand , rented) values ('double bass', 'Gibson', false);
insert into instrument_in_stock (instrument, brand , rented) values ('piano', 'Shure', false);
insert into instrument_in_stock (instrument, brand , rented) values ('piano', 'Gibson', true);
insert into instrument_in_stock (instrument, brand , rented) values ('guitar', 'Sennheiser', true);
insert into instrument_in_stock (instrument, brand , rented) values ('double bass', 'Roland', false);
insert into instrument_in_stock (instrument, brand , rented) values ('trumpet', 'Fender Musical', true);
insert into instrument_in_stock (instrument, brand , rented) values ('double bass', 'Gibson', true);
insert into instrument_in_stock (instrument, brand , rented) values ('fiol', 'Harman Professional', false);
insert into instrument_in_stock (instrument, brand , rented) values ('double bass', 'Harman Professional', false);
insert into instrument_in_stock (instrument, brand , rented) values ('clarinett', 'Harman Professional', true);
insert into instrument_in_stock (instrument, brand , rented) values ('double bass', 'Roland', false);
insert into instrument_in_stock (instrument, brand , rented) values ('double bass', 'Roland', false);
insert into instrument_in_stock (instrument, brand , rented) values ('fiol', 'Gibson', true);
insert into instrument_in_stock (instrument, brand , rented) values ('piano', 'Shure', false);
insert into instrument_in_stock (instrument, brand , rented) values ('double bass', 'Harman Professional', false);
insert into instrument_in_stock (instrument, brand , rented) values ('guitar', 'Shure', true);
insert into instrument_in_stock (instrument, brand , rented) values ('trumpet', 'Gibson', false);
insert into instrument_in_stock (instrument, brand , rented) values ('harmonica', 'Harman Professional', true);
insert into instrument_in_stock (instrument, brand , rented) values ('double bass', 'Yamaha', false);
insert into instrument_in_stock (instrument, brand , rented) values ('violin', 'Shure', false);
insert into instrument_in_stock (instrument, brand , rented) values ('double bass', 'Harman Professional', true);
insert into instrument_in_stock (instrument, brand , rented) values ('piano', 'Sennheiser', false);
insert into instrument_in_stock (instrument, brand , rented) values ('saxophone', 'Shure', true);
insert into instrument_in_stock (instrument, brand , rented) values ('saxophone', 'Harman Professional', true);
insert into instrument_in_stock (instrument, brand , rented) values ('trumpet', 'Shure', false);
insert into instrument_in_stock (instrument, brand , rented) values ('violin', 'Harman Professional', true);
insert into instrument_in_stock (instrument, brand , rented) values ('piano', 'Yamaha', false);
insert into instrument_in_stock (instrument, brand , rented) values ('violin', 'Shure', false);
insert into instrument_in_stock (instrument, brand , rented) values ('fiol', 'Harman Professional', true);
insert into instrument_in_stock (instrument, brand , rented) values ('double bass', 'Yamaha', false);
insert into instrument_in_stock (instrument, brand , rented) values ('clarinett', 'Shure', true);
insert into instrument_in_stock (instrument, brand , rented) values ('trumpet', 'Roland', false);
insert into instrument_in_stock (instrument, brand , rented) values ('double bass', 'Harman Professional', true);
insert into instrument_in_stock (instrument, brand , rented) values ('harmonica', 'Yamaha', false);
insert into instrument_in_stock (instrument, brand , rented) values ('violin', 'Roland', true);
insert into instrument_in_stock (instrument, brand , rented) values ('guitar', 'Yamaha', true);
insert into instrument_in_stock (instrument, brand , rented) values ('trumpet', 'Yamaha', true);
insert into instrument_in_stock (instrument, brand , rented) values ('saxophone', 'Yamaha', false);
insert into instrument_in_stock (instrument, brand , rented) values ('violin', 'Gibson', true);
insert into instrument_in_stock (instrument, brand , rented) values ('guitar', 'Gibson', true);
insert into instrument_in_stock (instrument, brand , rented) values ('violin', 'Gibson', true);
insert into instrument_in_stock (instrument, brand , rented) values ('double bass', 'Shure', true);
insert into instrument_in_stock (instrument, brand , rented) values ('cello', 'Harman Professional', true);
insert into instrument_in_stock (instrument, brand , rented) values ('clarinett', 'Harman Professional', true);
insert into instrument_in_stock (instrument, brand , rented) values ('fiol', 'Roland', true);
insert into instrument_in_stock (instrument, brand , rented) values ('cello', 'Roland', true);
insert into instrument_in_stock (instrument, brand , rented) values ('saxophone', 'Gibson', false);
insert into instrument_in_stock (instrument, brand , rented) values ('guitar', 'Roland', true);
insert into instrument_in_stock (instrument, brand , rented) values ('double bass', 'Gibson', true);

insert into price (type, level, price ) values ('ensamble', NULL, 100);
insert into price (type, level, price ) values ('group', 'beginner',200 );
insert into price (type, level, price ) values ('group', 'intermediate', 300);
insert into price (type, level, price ) values ('individual', NULL, 500);
insert into price (type, level, price ) values ('group', 'advanced', 400);


insert into student_sibling (student_id, student_id_0) values (28, 6);
insert into student_sibling (student_id, student_id_0) values (12, 20);
insert into student_sibling (student_id, student_id_0) values (21, 12);
insert into student_sibling (student_id, student_id_0) values (22, 14);
insert into student_sibling (student_id, student_id_0) values (23, 17);
insert into student_sibling (student_id, student_id_0) values (20, 9);
insert into student_sibling (student_id, student_id_0) values (3, 1);
insert into student_sibling (student_id, student_id_0) values (9, 15);
insert into student_sibling (student_id, student_id_0) values (28, 7);
insert into student_sibling (student_id, student_id_0) values (17, 9);

insert into contact_person (first_name, email, person_number, sur_name, phone, student_id ) values ('Elladine', 'evinten0@discovery.com', '3695930942', 'Vinten', '9803371660', 15);
insert into contact_person (first_name, email, person_number, sur_name, phone, student_id ) values ('Celene', 'chatry1@wordpress.com', '7188552681', 'Hatry', '2941496706', 23);
insert into contact_person (first_name, email, person_number, sur_name, phone, student_id ) values ('Sunny', 'smeads2@devhub.com', '7794244811', 'Meads', '2299467852', 26);
insert into contact_person (first_name, email, person_number, sur_name, phone, student_id ) values ('Maxi', 'mtreherne3@ustream.tv', '5532235074', 'Treherne', '4937681018', 16);
insert into contact_person (first_name, email, person_number, sur_name, phone, student_id ) values ('Jory', 'jstandidge4@ocn.ne.jp', '7135728718', 'Standidge', '1081631052', 12);
insert into contact_person (first_name, email, person_number, sur_name, phone, student_id ) values ('Sella', 'sdansken5@surveymonkey.com', '3078644243', 'Dansken', '6804024062', 14);
insert into contact_person (first_name, email, person_number, sur_name, phone, student_id ) values ('Mirabella', 'mlevecque6@cafepress.com', '8241592086', 'Levecque', '1211897690', 19);
insert into contact_person (first_name, email, person_number, sur_name, phone, student_id ) values ('Farlee', 'fhuby7@ihg.com', '8393465036', 'Huby', '3358309910', 17);
insert into contact_person (first_name, email, person_number, sur_name, phone, student_id ) values ('Saul', 'sfaulds8@biblegateway.com', '7473009575', 'Faulds', '6515465753', 14);
insert into contact_person (first_name, email, person_number, sur_name, phone, student_id) values ('Robers', 'rmoncrefe9@fc2.com', '4604471908', 'Moncrefe', '7397894451', 5);

insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('SA', 'punk', 6, 11, '2022-04-20 20:00:55', 19, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('AS', 'punk rock', 6, 11, '2022-07-09 06:33:48', 24, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('OC', 'classical', 5, 10, '2022-11-17 01:18:59', 15, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('OC', 'rock', 6, 11, '2022-01-20 21:38:29', 14, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('AF', 'punk', 6, 11, '2022-09-20 19:00:23', 17, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('SA', 'punk rock', 15, 20, '2022-06-29 16:22:03', 7, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('NA', 'classical', 8, 13, '2022-12-11 07:40:17', 29, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('AS', 'punk rock', 13, 18, '2022-10-30 03:35:31', 14, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('EU', 'punk', 6, 11, '2022-03-11 19:54:10', 20, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('NA', 'jazz', 11, 16, '2022-05-10 14:34:31', 13, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('AF', 'punk', 7, 12, '2022-04-18 21:01:36', 17, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('NA', 'jazz', 15, 20, '2022-04-16 15:59:52', 5, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('EU', 'rock', 6, 11, '2022-08-25 06:50:27', 6, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('EU', 'punk', 12, 17, '2022-05-14 00:07:04', 22, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('EU', 'classical', 13, 18, '2022-03-02 01:11:35', 9, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('NA', 'classical', 12, 17, '2022-11-04 08:13:14', 28, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('AS', 'jazz', 7, 12, '2022-06-21 06:45:01', 28, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('NA', 'classical', 10, 15, '2022-10-30 15:00:06', 6, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('EU', 'rock', 6, 11, '2022-06-06 16:57:42', 4, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('NA', 'classical', 12, 17, '2022-11-10 14:36:41', 2, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('NA', 'jazz', 10, 15, '2022-06-18 21:19:19', 14, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('NA', 'punk rock', 14, 19, '2022-08-18 13:46:59', 2, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('EU', 'punk', 15, 20, '2022-09-17 22:35:42', 7, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('NA', 'rock', 11, 16, '2022-11-30 06:03:42', 29, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('AS', 'punk', 15, 20, '2022-04-30 02:40:04', 2, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('NA', 'punk rock', 11, 16, '2022-05-27 17:12:12', 20, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('AF', 'rock', 14, 19, '2022-12-28 23:17:43', 29, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('AS', 'rock', 12, 17, '2022-08-18 17:22:23', 29, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('SA', 'jazz', 8, 13, '2022-05-28 03:08:40', 22, 1);
insert into ensamble (place, target_genre, min_participants, max_participants, date_and_time, instructor_id, price_id) values ('NA', 'jazz', 6, 11, '2022-10-05 13:55:14', 22, 1);

insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('harmonica', 14, 19, 'intermediate', '2022-01-29 10:02:40', 'AS', 5, 19);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('cello', 14, 19, 'advanced', '2022-07-09 07:57:20', 'OC', 3, 16);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('saxophone', 11, 16, 'beginner', '2022-03-12 20:59:48', 'EU', 3, 26);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('piano', 6, 11, 'beginner', '2022-12-25 16:36:53', 'OC', 5, 20);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('cello', 13, 18, 'intermediate', '2022-11-23 12:13:32', 'NA', 5, 26);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('piano', 8, 13, 'beginner', '2022-01-28 02:35:56', 'EU', 3, 14);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('clarinett', 14, 19, 'advanced', '2022-08-10 00:55:29', 'NA', 2, 23);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('trumpet', 6, 11, 'intermediate', '2022-05-14 13:32:46', 'AF', 3, 23);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('harmonica', 13, 18, 'advanced', '2022-11-13 17:44:29', 'SA', 5, 27);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('violin', 11, 16, 'advanced', '2022-07-25 09:24:20', 'SA', 2, 5);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('trumpet', 14, 19, 'beginner', '2022-04-24 16:40:04', 'EU', 5, 9);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('cello', 10, 15, 'advanced', '2022-05-30 13:30:21', 'EU', 3, 13);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('clarinett', 15, 20, 'beginner', '2022-08-31 13:29:05', 'NA', 3, 30);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('trumpet', 7, 12, 'intermediate', '2022-08-05 05:30:00', 'OC', 5, 11);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('cello', 6, 11, 'advanced', '2022-11-25 08:07:51', 'NA', 2, 21);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('saxophone', 9, 14, 'intermediate', '2022-06-10 12:51:10', 'SA', 5, 24);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('fiol', 9, 14, 'beginner', '2022-12-16 08:45:24', 'AF', 2, 21);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('harmonica', 7, 12, 'beginner', '2022-01-06 00:41:43', 'SA', 3, 11);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('harmonica', 14, 19, 'intermediate', '2022-03-06 18:08:32', 'NA', 5, 8);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('violin', 15, 20, 'intermediate', '2022-07-27 22:35:49', 'AS', 2, 12);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('piano', 7, 12, 'advanced', '2022-05-08 13:22:50', 'OC', 5, 24);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('guitar', 5, 10, 'advanced', '2022-01-07 02:09:47', 'NA', 2, 19);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('guitar', 5, 10, 'beginner', '2022-04-04 13:40:11', 'OC', 3, 6);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('trumpet', 15, 20, 'advanced', '2022-05-06 19:44:21', 'EU', 5, 28);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('piano', 11, 16, 'advanced', '2022-01-14 23:39:15', 'AS', 2, 29);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('cello', 9, 14, 'beginner', '2022-12-17 21:52:04', 'AF', 2, 19);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('violin', 9, 14, 'advanced', '2022-11-09 09:17:00', 'AS', 3, 24);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('violin', 9, 14, 'advanced', '2022-05-30 21:57:38', 'OC', 3, 21);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('cello', 13, 18, 'advanced', '2022-12-08 07:45:46', 'SA', 2, 2);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('violin', 13, 18, 'beginner', '2022-05-24 08:47:58', 'AS', 2, 7)
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('clarinett', 13, 18, 'intermediate', '2021-01-04 19:36:11', 'NA', 2, 8);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('double bass', 13, 18, 'intermediate', '2021-12-22 08:18:06', 'SA', 3, 5);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('harmonica', 5, 10, 'advanced', '2021-12-07 07:38:47', 'AS', 3, 16);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('fiol', 15, 20, 'advanced', '2021-10-02 17:03:19', 'OC', 3, 14);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('saxophone', 10, 15, 'intermediate', '2021-07-19 17:42:02', 'AS', 3, 9);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('violin', 15, 20, 'advanced', '2021-07-04 02:11:52', 'EU', 5, 21);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('trumpet', 11, 16, 'beginner', '2021-05-15 20:08:27', 'NA', 2, 1);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('double bass', 14, 19, 'beginner', '2021-02-11 23:39:53', 'NA', 2, 15);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('cello', 11, 16, 'beginner', '2021-12-14 05:21:29', 'AF', 2, 27);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('piano', 5, 10, 'intermediate', '2021-11-01 20:57:08', 'OC', 2, 30);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('trumpet', 11, 16, 'intermediate', '2021-11-13 15:58:41', 'NA', 2, 23);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('cello', 12, 17, 'advanced', '2021-01-22 08:39:59', 'AF', 2, 22);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('guitar', 7, 12, 'advanced', '2021-02-21 16:12:04', 'AF', 2, 11);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('clarinett', 13, 18, 'intermediate', '2021-05-12 23:33:11', 'SA', 2, 7);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('guitar', 15, 20, 'intermediate', '2021-10-22 14:27:37', 'NA', 5, 11);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('violin', 6, 11, 'advanced', '2021-10-31 04:02:48', 'AS', 5, 17);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('trumpet', 12, 17, 'advanced', '2021-07-29 16:32:33', 'EU', 3, 10);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('violin', 6, 11, 'intermediate', '2021-10-16 00:58:57', 'OC', 2, 25);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('cello', 10, 15, 'intermediate', '2021-04-24 12:07:39', 'SA', 5, 3);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('trumpet', 6, 11, 'advanced', '2021-04-13 03:22:09', 'OC', 2, 20);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('guitar', 9, 14, 'intermediate', '2021-01-11 22:18:52', 'NA', 3, 15);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('trumpet', 5, 10, 'intermediate', '2021-03-07 17:48:44', 'OC', 3, 3);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('piano', 7, 12, 'intermediate', '2021-11-13 15:22:17', 'NA', 5, 14);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('saxophone', 8, 13, 'intermediate', '2021-10-26 05:23:04', 'OC', 5, 11);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('cello', 8, 13, 'intermediate', '2021-08-18 04:03:25', 'AF', 2, 18);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('fiol', 8, 13, 'intermediate', '2021-05-24 21:45:35', 'AF', 3, 3);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('clarinett', 10, 15, 'beginner', '2021-07-09 20:37:16', 'AF', 2, 26);
insert into group_lesson (instrument, min_participants, max_participants, level, date_and_time, place, price_id, instructor_id ) values ('harmonica', 7, 12, 'intermediate', '2021-06-30 08:37:08', 'AS', 3, 8);

insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-10-04 20:51:28', 6, 4, 'OC', 23);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-10-15 10:42:41', 25, 4, 'EU', 12);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-08-27 13:55:02', 14, 4, 'AF', 24);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-03-26 11:29:16', 22, 4, 'EU', 17);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2021-12-17 21:59:55', 29, 4, 'AS', 18);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-01-01 08:11:50', 9, 4, 'AF', 22);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-06-23 14:48:26', 10, 4, 'NA', 19);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2021-12-22 10:04:03', 16, 4, 'NA', 2);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-08-25 01:51:18', 21, 4, 'NA', 10);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-03-15 10:26:22', 8, 4, 'AF', 8);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-07-29 10:34:51', 11, 4, 'AS', 9);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-10-23 03:13:58', 30, 4, 'NA', 24);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-11-08 20:51:30', 20, 4, 'AF', 18);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-05-07 14:08:25', 14, 4, 'EU', 25);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-04-20 19:45:30', 28, 4, 'NA', 17);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-07-11 17:06:16', 4, 4, 'AF', 18);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-04-20 22:38:02', 3, 4, 'OC', 16);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-03-20 15:41:34', 17, 4, 'NA', 26);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-06-16 05:56:56', 28, 4, 'OC', 24);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-06-08 06:59:48', 20, 4, 'NA', 2);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-05-20 08:17:22', 15, 4, 'AS', 7);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-08-09 13:10:12', 21, 4, 'AS', 4);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-11-02 08:21:06', 15, 4, 'AS', 29);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-03-16 04:40:43', 21, 4, 'EU', 23);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-03-11 10:23:33', 14, 4, 'NA', 15);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-11-02 09:32:23', 29, 4, 'AS', 13);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-08-06 04:23:34', 30, 4, 'AS', 2);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-09-23 23:29:06', 29, 4, 'NA', 19);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-07-10 07:26:37', 27, 4, 'AF', 22);
insert into individual_lesson (date_and_time, student_id, price_id, place, instructor_id) values ('2022-07-06 23:43:05', 11, 4, 'AS', 4);

insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (8, 200, '2022-06-10 19:48:14', '2022-07-10 19:48:14', 14);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (19, 200, '2022-03-22 12:01:51', '2022-04-21 12:01:51', 27);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (21, 200, '2022-09-04 02:17:39', '2022-10-04 02:17:39', 2);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (11, 200, '2022-10-06 19:09:58', '2022-11-05 19:09:58', 30);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (11, 200, '2022-10-26 18:22:09', '2022-11-25 18:22:09', 21);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (11, 200, '2022-11-11 11:13:50', '2022-12-11 11:13:50', 16);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (27, 200, '2022-01-13 09:48:54', '2022-02-12 09:48:54', 8);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (30, 200, '2022-04-14 23:54:50', '2022-05-14 23:54:50', 4);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (10, 200, '2022-10-03 07:27:10', '2022-11-02 07:27:10', 25);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (12, 200, '2022-09-19 02:54:31', '2022-10-19 02:54:31', 5);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (28, 200, '2022-01-22 18:31:41', '2022-02-21 18:31:41', 27);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (3, 200, '2022-07-22 09:08:51', '2022-08-21 09:08:51', 21);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (1, 200, '2022-12-21 16:35:05', '2023-01-20 16:35:05', 11);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (18, 200, '2022-03-14 21:30:05', '2022-04-13 21:30:05', 19);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (26, 200, '2022-10-13 01:16:00', '2022-11-12 01:16:00', 9);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (30, 200, '2022-03-31 01:43:38', '2022-04-30 01:43:38', 6);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (6, 200, '2022-08-21 17:36:58', '2022-09-20 17:36:58', 8);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (8, 200, '2022-08-07 03:38:36', '2022-09-06 03:38:36', 26);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (10, 200, '2022-02-26 03:02:04', '2022-03-28 03:02:04', 22);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (27, 200, '2022-01-01 18:28:26', '2022-01-31 18:28:26', 10);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (16, 200, '2022-04-07 12:17:53', '2022-05-07 12:17:53', 18);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (15, 200, '2022-05-01 06:05:23', '2022-05-31 06:05:23', 11);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (19, 200, '2022-07-22 05:10:24', '2022-08-21 05:10:24', 7);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (3, 200, '2022-01-20 13:20:55', '2022-02-19 13:20:55', 25);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (12, 200, '2022-12-07 21:07:53', '2023-01-06 21:07:53', 9);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (21, 200, '2022-01-11 16:29:25', '2022-02-10 16:29:25', 26);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (23, 200, '2022-03-08 14:37:32', '2022-04-07 14:37:32', 29);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (8, 200, '2022-11-21 17:24:27', '2022-12-21 17:24:27', 15);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (1, 200, '2022-05-01 21:24:05', '2022-05-31 21:24:05', 7);
insert into rent_instrument (instrument_in_stock_id, fee, start_at, end_at, student_id) values (24, 200, '2022-11-27 14:48:13', '2022-12-27 14:48:13', 19);


insert into skill_level (student_id, instrument , level) values (2, 'guitar', 'advanced');
insert into skill_level (student_id, instrument , level) values (18, 'cello', 'intermediate');
insert into skill_level (student_id, instrument , level) values (1, 'violin', 'beginner');
insert into skill_level (student_id, instrument , level) values (21, 'trumpet', 'intermediate');
insert into skill_level (student_id, instrument , level) values (26, 'guitar', 'intermediate');
insert into skill_level (student_id, instrument , level) values (21, 'fiol', 'intermediate');
insert into skill_level (student_id, instrument , level) values (6, 'double bass', 'advanced');
insert into skill_level (student_id, instrument , level) values (23, 'double bass', 'beginner');
insert into skill_level (student_id, instrument , level) values (12, 'harmonica', 'intermediate');
insert into skill_level (student_id, instrument , level) values (5, 'guitar', 'beginner');
insert into skill_level (student_id, instrument , level) values (9, 'clarinett', 'advanced');
insert into skill_level (student_id, instrument , level) values (10, 'trumpet', 'beginner');
insert into skill_level (student_id, instrument , level) values (22, 'guitar', 'beginner');
insert into skill_level (student_id, instrument , level) values (4, 'piano', 'advanced');
insert into skill_level (student_id, instrument , level) values (17, 'fiol', 'intermediate');
insert into skill_level (student_id, instrument , level) values (11, 'harmonica', 'advanced');
insert into skill_level (student_id, instrument , level) values (25, 'saxophone', 'advanced');
insert into skill_level (student_id, instrument , level) values (20, 'piano', 'intermediate');
insert into skill_level (student_id, instrument , level) values (24, 'piano', 'advanced');
insert into skill_level (student_id, instrument , level) values (10, 'harmonica', 'intermediate');
insert into skill_level (student_id, instrument , level) values (18, 'piano', 'beginner');
insert into skill_level (student_id, instrument , level) values (6, 'fiol', 'intermediate');
insert into skill_level (student_id, instrument , level) values (7, 'guitar', 'beginner');
insert into skill_level (student_id, instrument , level) values (4, 'trumpet', 'intermediate');
insert into skill_level (student_id, instrument , level) values (26, 'clarinett', 'intermediate');
insert into skill_level (student_id, instrument , level) values (12, 'violin', 'intermediate');
insert into skill_level (student_id, instrument , level) values (16, 'piano', 'intermediate');
insert into skill_level (student_id, instrument , level) values (28, 'violin', 'advanced');
insert into skill_level (student_id, instrument , level) values (6, 'clarinett', 'advanced');
insert into skill_level (student_id, instrument , level) values (30, 'piano', 'beginner');
insert into skill_level (student_id, instrument , level) values (18, 'cello', 'advanced');
insert into skill_level (student_id, instrument , level) values (2, 'harmonica', 'advanced');
insert into skill_level (student_id, instrument , level) values (4, 'piano', 'beginner');
insert into skill_level (student_id, instrument , level) values (23, 'guitar', 'advanced');
insert into skill_level (student_id, instrument , level) values (20, 'fiol', 'intermediate');
insert into skill_level (student_id, instrument , level) values (1, 'cello', 'intermediate');
insert into skill_level (student_id, instrument , level) values (24, 'clarinett', 'advanced');
insert into skill_level (student_id, instrument , level) values (12, 'cello', 'intermediate');
insert into skill_level (student_id, instrument , level) values (11, 'piano', 'intermediate');
insert into skill_level (student_id, instrument , level) values (19, 'fiol', 'advanced');
insert into skill_level (student_id, instrument , level) values (29, 'cello', 'intermediate');
insert into skill_level (student_id, instrument , level) values (19, 'guitar', 'advanced');
insert into skill_level (student_id, instrument , level) values (16, 'cello', 'beginner');
insert into skill_level (student_id, instrument , level) values (11, 'harmonica', 'beginner');
insert into skill_level (student_id, instrument , level) values (17, 'clarinett', 'beginner');
insert into skill_level (student_id, instrument , level) values (6, 'piano', 'advanced');
insert into skill_level (student_id, instrument , level) values (24, 'clarinett', 'advanced');
insert into skill_level (student_id, instrument , level) values (25, 'violin', 'advanced');
insert into skill_level (student_id, instrument , level) values (27, 'piano', 'intermediate');
insert into skill_level (student_id, instrument , level) values (6, 'cello', 'beginner');

insert into student_ensamble (student_id , ensamble_id ) values (17, 25);
insert into student_ensamble (student_id , ensamble_id ) values (6, 17);
insert into student_ensamble (student_id , ensamble_id ) values (16, 22);
insert into student_ensamble (student_id , ensamble_id ) values (6, 19);
insert into student_ensamble (student_id , ensamble_id ) values (28, 27);
insert into student_ensamble (student_id , ensamble_id ) values (19, 16);
insert into student_ensamble (student_id , ensamble_id ) values (17, 24);
insert into student_ensamble (student_id , ensamble_id ) values (6, 5);
insert into student_ensamble (student_id , ensamble_id ) values (2, 17);
insert into student_ensamble (student_id , ensamble_id ) values (24, 24);
insert into student_ensamble (student_id , ensamble_id ) values (6, 7);
insert into student_ensamble (student_id , ensamble_id ) values (10, 21);
insert into student_ensamble (student_id , ensamble_id ) values (22, 17);
insert into student_ensamble (student_id , ensamble_id ) values (6, 24);
insert into student_ensamble (student_id , ensamble_id ) values (18, 29);
insert into student_ensamble (student_id , ensamble_id ) values (28, 23);
insert into student_ensamble (student_id , ensamble_id ) values (18, 25);
insert into student_ensamble (student_id , ensamble_id ) values (3, 2);
insert into student_ensamble (student_id , ensamble_id ) values (6, 9);
insert into student_ensamble (student_id , ensamble_id ) values (16, 9);
insert into student_ensamble (student_id , ensamble_id ) values (6, 17);
insert into student_ensamble (student_id , ensamble_id ) values (20, 18);
insert into student_ensamble (student_id , ensamble_id ) values (3, 29);
insert into student_ensamble (student_id , ensamble_id ) values (18, 19);
insert into student_ensamble (student_id , ensamble_id ) values (17, 12);
insert into student_ensamble (student_id , ensamble_id ) values (5, 25);
insert into student_ensamble (student_id , ensamble_id ) values (18, 20);
insert into student_ensamble (student_id , ensamble_id ) values (3, 13);
insert into student_ensamble (student_id , ensamble_id ) values (19, 18);
insert into student_ensamble (student_id , ensamble_id ) values (12, 8);


insert into student_group_lesson (student_id , group_lesson_id ) values (29, 12);
insert into student_group_lesson (student_id , group_lesson_id ) values (2, 5);
insert into student_group_lesson (student_id , group_lesson_id ) values (8, 21);
insert into student_group_lesson (student_id , group_lesson_id ) values (28, 3);
insert into student_group_lesson (student_id , group_lesson_id ) values (16, 4);
insert into student_group_lesson (student_id , group_lesson_id ) values (16, 5);
insert into student_group_lesson (student_id , group_lesson_id ) values (11, 25);
insert into student_group_lesson (student_id , group_lesson_id ) values (2, 10);
insert into student_group_lesson (student_id , group_lesson_id ) values (16, 22);
insert into student_group_lesson (student_id , group_lesson_id ) values (8, 1);
insert into student_group_lesson (student_id , group_lesson_id ) values (25, 12);
insert into student_group_lesson (student_id , group_lesson_id ) values (21, 22);
insert into student_group_lesson (student_id , group_lesson_id ) values (4, 3);
insert into student_group_lesson (student_id , group_lesson_id ) values (29, 3);
insert into student_group_lesson (student_id , group_lesson_id ) values (20, 10);
insert into student_group_lesson (student_id , group_lesson_id ) values (19, 24);
insert into student_group_lesson (student_id , group_lesson_id ) values (24, 21);
insert into student_group_lesson (student_id , group_lesson_id ) values (6, 15);
insert into student_group_lesson (student_id , group_lesson_id ) values (15, 25);
insert into student_group_lesson (student_id , group_lesson_id ) values (20, 25);
insert into student_group_lesson (student_id , group_lesson_id ) values (19, 7);
insert into student_group_lesson (student_id , group_lesson_id ) values (1, 9);
insert into student_group_lesson (student_id , group_lesson_id ) values (11, 13);
insert into student_group_lesson (student_id , group_lesson_id ) values (20, 22);
insert into student_group_lesson (student_id , group_lesson_id ) values (4, 28);
insert into student_group_lesson (student_id , group_lesson_id ) values (28, 13);
insert into student_group_lesson (student_id , group_lesson_id ) values (17, 27);
insert into student_group_lesson (student_id , group_lesson_id ) values (24, 1);
insert into student_group_lesson (student_id , group_lesson_id ) values (20, 14);
insert into student_group_lesson (student_id , group_lesson_id ) values (24, 18);